name: Daily Uptime Ping

on:
  schedule:
    - cron: "30 18 * * *" # 12:00 AM IST (UTC+5:30)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Cloudflare Worker
        env:
          WORKER_URL: ${{ secrets.WORKER_URL }}
        run: |
          echo "Pinging $WORKER_URL..."
          curl -sSf "$WORKER_URL" || echo "Ping failed"
